### PR TITLE
fix: export lib for umd

### PR DESCRIPTION
**Pull request by Inqnuam**
Now UMD should work 😉

### CODE REVIEW

**Comment by Inqnuam** [comment]
This works in browser, but will fail in NodeJS, let me to add some fixes !

**Comment by dy** [comment]
Nah, we can't have a separate entry, also we really need to have `window.sprae` as a function.
Thanks for the PR but we'll stick to sprae.auto.js for now

**Comment by Inqnuam** [comment]
with this PR `window.sprae` works as a function.

What do you mean by "separate entry" ?

with this UMD output you can run your app in any JavaScript runtime:
- from global scope ("windows", "globalThis", "self")
- with an AMD loader like RequireJS
- or with `require()`

**Comment by dy** [comment]
> What do you mean by "separate entry"

I mean the proposed `sprae.umd.cjs` at the root - the top level entries are importable. I was hoping it's possible to be done via `footer` in build options. Do you think if that's possible?

> with this UMD output you can run your app in any JavaScript runtime

Would be nice improvement, I sort-of gave up on UMD, it seems like investing into obsolete tech.

**Comment by Inqnuam** [comment]
@dy 
> I was hoping it's possible to be done via footer in build options. Do you think if that's possible?

its possible to completely get ride of `sprae.umd.cjs` file using esbuild's [stdin  option](https://esbuild.github.io/api/#stdin).

> Would be nice improvement, but I sort-of gave up on CJS/AMD, it seems like investing into obsolete tech.

Agree, it could still be relevant depending on target browser.
Personally and professionally I never use or promote UMD.

my understanding of your UMD usage is:
- if sprae runs in browser, attach sprae to window
- then launch the "auto-init" feature

Correct me if I'm wrong but if this is the only use case, then there's a much easier way to achieve your needs, let me know if you need help

**Comment by Inqnuam** [comment]
```js
// Standalone build
await esbuild.build({
  stdin: {
    contents: `import sprae from "./sprae.js";
// standalone run
if (typeof document != "undefined" && document?.currentScript) {
  window.sprae = sprae
  if (document.currentScript.hasAttribute('init')) sprae(document.documentElement);
}`, 
    resolveDir: "./",
    sourcefile: "auto-init"
  },
  outfile: "dist/sprae.auto.js",
  bundle: true,
  target: 'es2020',
  sourcemap: 'external',
  format: "iife"
})
esbuild.build({
  entryPoints: ['dist/sprae.auto.js'],
  outfile: "dist/sprae.auto.min.js",
  sourcemap: 'external',
  minify: true
})
```

**Comment by dy** [comment]
Giving it a second thought

**Comment by dy** [comment]
.

**Comment by dy** [comment]
.

**Comment by dy** [comment]
.

**Comment by dy** [comment]
Giving it a second thought. If you'd like to reopen that PR I can merge it.
Maybe `sprae.auto.js` root entry would make sense.

**Comment by dy** [comment]
@Inqnuam thanks, in fact you were right, I should've taken your PR. I've incorporated change anyways.

**Pull request closed without merging**
